package org.springframework.samples.petclinic.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PetTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPetTypeAllPropertiesEquals(PetType expected, PetType actual) {
        assertPetTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertPetTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPetTypeAllUpdatablePropertiesEquals(PetType expected, PetType actual) {
        assertPetTypeUpdatableFieldsEquals(expected, actual);
        assertPetTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPetTypeAutoGeneratedPropertiesEquals(PetType expected, PetType actual) {
        assertThat(expected)
            .as("Verify PetType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPetTypeUpdatableFieldsEquals(PetType expected, PetType actual) {
        assertThat(expected)
            .as("Verify PetType relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPetTypeUpdatableRelationshipsEquals(PetType expected, PetType actual) {}
}
