package org.springframework.samples.petclinic.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.samples.petclinic.domain.AssertUtils.bigDecimalCompareTo;

public class VetAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVetAllPropertiesEquals(Vet expected, Vet actual) {
        assertVetAutoGeneratedPropertiesEquals(expected, actual);
        assertVetAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVetAllUpdatablePropertiesEquals(Vet expected, Vet actual) {
        assertVetUpdatableFieldsEquals(expected, actual);
        assertVetUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVetAutoGeneratedPropertiesEquals(Vet expected, Vet actual) {
        assertThat(expected)
            .as("Verify Vet auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVetUpdatableFieldsEquals(Vet expected, Vet actual) {
        assertThat(expected)
            .as("Verify Vet relevant properties")
            .satisfies(e -> assertThat(e.getFirstName()).as("check firstName").isEqualTo(actual.getFirstName()))
            .satisfies(e -> assertThat(e.getLastName()).as("check lastName").isEqualTo(actual.getLastName()))
            .satisfies(
                e -> assertThat(e.getSalary()).as("check salary").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getSalary())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVetUpdatableRelationshipsEquals(Vet expected, Vet actual) {
        assertThat(expected)
            .as("Verify Vet relationships")
            .satisfies(e -> assertThat(e.getSpecialities()).as("check specialities").isEqualTo(actual.getSpecialities()));
    }
}
